### ISSUE TITLE
bug:Anonymous avatar and username not updating properly/not showing

### ISSUE THREAD

**Issue by brotherIy** [swmff/sparkler#13]
Other people I have talked to also had this problem, no matter how many times they update their profile, both the avatar and username of anonymous users never change to the chosen ones; even after trying to change it in multiple devices and image hosting sites. Other images in the page work fine.
![image](https://github.com/user-attachments/assets/67f535c2-b990-4680-82a0-9103828f46aa)
![image](https://github.com/user-attachments/assets/46528d0e-9031-4fd5-ad4b-64f855a8db34)

**Comment by trisuaso** [comment]
Should be fixed now, thanks!

Feel free to reopen if I missed a spot where these should show.
