### ISSUE TITLE
bug: Edititing posts doesn't work

### ISSUE THREAD

**Issue by fleshorchestra** [swmff/sparkler#14]
Whenever I try to edit a post within the first 2 hours of posting it, I get a box that says "You are not allowed to do this"

![IMG_1042](https://github.com/user-attachments/assets/07e7d1cb-8ba4-4129-b448-f08901bcb0f4)

I keep having to delete posts and resend myself things if I want to edit something such as a typo or incorrect markdown

**Comment by trisuaso** [comment]
Fixed, thank you!
