### ISSUE TITLE
feature: No limit for edit button

### ISSUE THREAD

**Issue by fleshorchestra** [swmff/sparkler#15]
I think it would be really useful and beneficial for users to be able to go and edit any posts at any time, even if it's months after being posted. 2 hours can sometimes not be enough time to recognize issues with a post, or want to add something else. At least maybe 24 hours instead of only 2, if making it unlimited isn't possible. But unlimited editing would be amazing honestly. It would help users curate their online space much easier no matter how much time passes.

**Comment by trisuaso** [comment]
This has been adjusted to 24 hours.

Likely never going to go unlimited because we don't store an edit history, so that opens responses up to people just getting out of trouble by editing their responses.
