### ISSUE TITLE
bug: Edit button doesn't work (again)

### ISSUE THREAD

**Issue by fleshorchestra** [swmff/sparkler#16]
Sorry for the excessive issue requests in regards to the edit button

After the recent update expanding the timeframe from 2 hours to 24 hours, the edit button doesn't work at all anymore. When you press the button to "confirm" a post being edited, there is not even a popup that states an error like "You can't do this" the button just does nothing.

**Comment by trisuaso** [comment]
You're completely right, not sure how I missed this! Thanks.
