### ISSUE TITLE
bug: discrepancy in comment length

### ISSUE THREAD

**Issue by nilsding** [swmff/sparkler#3]
**Describe the bug**
When trying to post a long comment (> 250 characters), the comment will be gone and you'll be greeted with a `Content too long!` error.

**To Reproduce**
1. Go to any response
2. Write a long comment over 250 characters and post it
5. Observe the error, and be sad that the comment is gone now.

**Expected behavior**

- the text box wouldn't allow me to write that much in the first place, OR
- the service just accepted that comment as-is

In any case, I'm still very sad about the comment that got sent to `/dev/null` :(  Tried navigating a page back, but it wasn't there anymore.

**Specifications**
Fedora Linux aarch64, latest Firefox

**Additional context**
I noticed this while trying to post a rather long comment -- the [frontend allows for 500 characters](https://github.com/swmff/sparkler/blob/67220195bbc3ea613b18a1e4af52cc863d32eea1/templates/response.html#L80) whereas the [database layer only allows a maximum of 250 characters](https://github.com/swmff/sparkler/blob/67220195bbc3ea613b18a1e4af52cc863d32eea1/src/database.rs#L1459-L1461).  I don't know which one should be the correct one -- that's up for you lot to decide.

Another nice-to-have would be a visible remaining characters counter ;-)

**Comment by trisuaso** [comment]
You're absolutely correct! A lot of the database stuff is boilerplate and I often forget to change some things... anywho I'd say 500 is likely correct because comments are shown on a separate page, so there's plenty of room.

I'll fix it tomorrow and probably add a remaining character counter as well! I'd imagine it would go something like this:
```js
app.define("hook.character_counter", function (_, event) {
    let target = event.target;

    while (!target.matches("textarea, input")) {
        target = target.parentElement;
    }

    const counter = document.getElementById(`${target.id}:counter`);
    counter.innerText = `${target.value.length}/${target.getAttribute("maxlength")}`;
});
```

will do in the morning.

**Comment by trisuaso** [comment]
I lied I'll do it now

**Comment by trisuaso** [comment]
Feel free to close if everything is satisfactory!

**Comment by nilsding** [comment]
Looks good now, thanks for the quick fix
