### ISSUE TITLE
bug: anonymous identifier is visible

### ISSUE THREAD

**Issue by pixeldesu** [swmff/sparkler#4]
**Describe the bug**

The anonymous identifier is visible

**To Reproduce**
1. Get an anonymous question or ask yourself one
2. Go to your inbox
3. Besides the "anonymous" text (or custom name) there is an identifier visible

**Expected behavior**

There is no anonymous identifier visible

**Additional context**

With the anonymous identifier visible, you don't have anonymity anymore, but rather pseudonymity because users are now identifiable by these aliases.

Unless a user decides to uncover themselves who they are (through the question body), an individual should not be able to discern which anonymous user is who.

Identifiers like this should be used strictly internally (for blocking a specific anonymous user, for example) or for moderation purposes only.

**Screenshots**
<img width="374" alt="Screenshot 2024-08-14 at 10 51 04" src="https://github.com/user-attachments/assets/640a71cd-4a35-44b9-8606-0cebaf8cf67e">

**Specifications**

* Arc 127.0.6533.100 (Official Build) (arm64)
* macOS Version 14.5 (Build 23F79)

**Comment by trisuaso** [comment]
Completely fair! Will be fixed.

**Comment by trisuaso** [comment]
Hidden, thank you!
