### ISSUE TITLE
bug: sanitized content can create empty entities

### ISSUE THREAD

**Issue by pixeldesu** [swmff/sparkler#5]
**Describe the bug**

If I create entities (like questions) with content that gets sanitized away, I create empty ones which technically shouldn't be possible, as the site validates against the inputs being empty.

**To Reproduce**
1. Go to a profile
2. Ask a question with the content `<iframe src="https://google.com"></iframe>`
3. Check the inbox
4. The question is empty

**Expected behavior**
If no content ends up visible/part of an entity, it shouldn't be created.

**Comment by trisuaso** [comment]
Fixed, thank you!

Feel free to reopen if you're still able to reproduce.
