### ISSUE TITLE
bug: you can pin responses of other users on your profile

### ISSUE THREAD

**Issue by pixeldesu** [swmff/sparkler#6]
**Describe the bug**

You can pin responses of other users on your profile using the input in the profile settings.

**To Reproduce**
1. Get the ID of another users answer
2. Copy it and go to your profile settings
3. Add the ID to the list of pinned responses
4. The response of another user shows up on your profile

**Expected behavior**
Answers not made by the user who pins them can't be pinned to that profile

**Screenshots**
<img width="1307" alt="Screenshot 2024-08-14 at 15 04 26" src="https://github.com/user-attachments/assets/91f5cc88-1db4-43d3-8106-bdf245f92370">

**Comment by trisuaso** [comment]
Fixed, thank you!

Feel free to open if you're still able to do this somehow. Shouldn't work now though because the response author is checked when rendering the template now.
