### ISSUE TITLE
bug: response count doesn't reset when account is recreated

### ISSUE THREAD

**Issue by pixeldesu** [swmff/sparkler#8]
**Describe the bug**

If I delete my profile and recreate it with the same username, the response count on my profile is the same as from the old account with no responses visible.

**To Reproduce**
1. Answer some questions
2. View the response count on your profile
3. Delete your account
4. Create a new account with the same name
5. Go on your profile
6. The response count is the same as on the old profile

**Expected behavior**
The response count should be 0.

**Additional context**
The issue probably stems from `xsulib.sparker.response_count:author_name` not being reset on profile deletion.

**Comment by trisuaso** [comment]
Fixed, thank you!

This was caused by me being dumb while writing `database.rs` for Sparkler, but not in `xsu-authman`.
