### ISSUE TITLE
bug: global questions can be answered multiple times

### ISSUE THREAD

**Issue by pixeldesu** [swmff/sparkler#9]
**Describe the bug**

The same user can answer global questions multiple times.

**To Reproduce**
1. Get a global question
2. Answer the global question
3. Answer the global question again

**Expected behavior**
A user can only answer a global question once.

**URLs**
https://sparkler.cc/question/212ab7fdb597edac33cae4f6e67e2fd8ebe64453b8a278753c944daeebb19fda

**Comment by trisuaso** [comment]
Fixed, thank you!

**Comment by pixeldesu** [comment]
@trisuaso works! I'd suggest additionally hiding the response form in the interface if you already answered. 

Getting a "You are not allowed to do this!" might be confusing to users. So it's best to not show the form at all to prevent this from popping up, or make the error message a bit more descriptive.

**Comment by trisuaso** [comment]
Should be better now!
